kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jane-admin
  namespace: dev
subjects:
- kind: User
  name: system:serviceaccount:dev:jane
  namespace: dev
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
