kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ken-view
  namespace: dev
subjects:
- kind: User
  name: system:serviceaccount:dev:ken
  namespace: dev
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
