apiVersion: v1
kind: Service
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  ports:
  - name: web
    protocol: TCP
    port: 80
  - name: metrics
    protocol: TCP
    port: 9113
  selector:
    app: web
  type: NodePort
