expose:
  type: ingress
  tls:
    enabled: true
    secretName: "harbor.34.91.22.70.nip.io"
  ingress:
    hosts:
      core: harbor.34.91.22.70.nip.io
    controller: default
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-production"

notary:
  enabled: false
