apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: shop-ingress
spec:
  rules:
  - host: shop.34.91.22.70.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
